image:
  file: .gitpod.Dockerfile

ports:
  - port: 8001
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
  - port: 8002
    onOpen: open-preview
  - port: 9000
    onOpen: ignore

tasks:
  - name: MySQL
    command: >
      mysql -e "create database bs_projectman;"
  - name: Nginx
    command: >
      nginx && multitail /var/log/nginx/access.log -I /var/log/nginx/error.log
  - name: Apache
    command: >
      apachectl start && php -v
  - name: Terminal
    command: >
      echo ""; echo "Commands you can try:"; echo " * nginx"; echo " * gp open
      /etc/nginx/nginx.conf"; echo " * gp open /var/log/nginx/access.log"; echo
      " * gp open /var/log/nginx/error.log";

vscode:
  extensions:
    - ktriek.ng-bootstrap-snippets@1.0.0:VUuHjE9V7Q9jWJGHFYuaag==
    - Mikael.Angular-BeastCode@8.0.10:J7aGjVXXDeyuqnhsk+vMYw==
    - CoenraadS.bracket-pair-colorizer@1.0.61:fqPT1sJEqaEdrfXeYbdW+A==
    - PKief.material-icon-theme@3.8.1:4hBEEejg04s1Ozsfu12fWQ==
    - steoates.autoimport@1.5.3:ssEPucpXsRjqSbJX1bW0YA==
    - esbenp.prettier-vscode@1.9.0:2CbWfKbh7qXJy3Ad4n/XgA==
    - ms-vscode.vscode-typescript-tslint-plugin@1.2.2:Jw3ra3MlKUzHrWQODXxjUw==
    - softwaredotcom.swdc-vscode@1.1.29:wMSd8WGlhnel1EhB8a47UA==
    - felixfbecker.php-debug@1.13.0:WX8Y3EpQk3zgahy41yJtNQ==
